module.exports = Object.freeze({
    PRODUCTS: [
        {table_id: '001', table_name: "roulette", table_type: "european"},
        {table_id: '002', table_name: "roulette", table_type: "american"},
        {table_id: '003', table_name: "roulette", table_type: "european"},
        {table_id: '004', table_name: "roulette", table_type: "american"},
        {table_id: '005', table_name: "blackjack"},
        {table_id: '006', table_name: "blackjack"},
        {table_id: '007', table_name: "blackjack"},
        {table_id: '008', table_name: "slots", table_type: "type1"},
        {table_id: '009', table_name: "slots", table_type: "type2"},
        {table_id: '010', table_name: "slots", table_type: "type1"},
        {table_id: '011', table_name: "slots", table_type: "type2"},
        {table_id: '012', table_name: "slots", table_type: "type1"},
        {table_id: '013', table_name: "craps"},
        {table_id: '014', table_name: "craps"},
        {table_id: '015', table_name: "craps"},
        {table_id: '016', table_name: "craps"},
        {table_id: '017', table_name: "craps"},
    ],
    MARKET: [        
        {id: "garlic", name_eng: "garlic", name_ro: "usturoi", price:0.1},
        {id: "onion", name_eng: "onion", name_ro: "ceapa", price:0.2},
        {id: "radish", name_eng: "radish", name_ro: "ridiche", price:0.5},
        {id: "carrot", name_eng: "carrot", name_ro: "morcov", price:1},
        {id: "turnip", name_eng: "turnip", name_ro: "nap", price:2},
        {id: "potato", name_eng: "potato", name_ro: "cartof", price:5},
        {id: "cabbage", name_eng: "cabbage", name_ro: "varza", price:10},
    ],
    CURRENCIES: [
        {id: "garlic", name_eng: "garlic", name_ro: "usturoi", price:0.1},
        {id: "onion", name_eng: "onion", name_ro: "ceapa", price:0.2},
        {id: "radish", name_eng: "radish", name_ro: "ridiche", price:0.5},
        {id: "carrot", name_eng: "carrot", name_ro: "morcov", price:1},
        {id: "turnip", name_eng: "turnip", name_ro: "nap", price:2},
        {id: "potato", name_eng: "potato", name_ro: "cartof", price:5},
        {id: "cabbage", name_eng: "cabbage", name_ro: "varza", price:10},
    ],
    PROFILES: [        
        {id: 1, name_eng: "weasel", name_ro: "nevastuica", free: true},
        {id: 2, name_eng: "fox", name_ro: "vulpe", free: false},
        {id: 3, name_eng: "wolf", name_ro: "lup", free: false},
        {id: 4, name_eng: "lynx", name_ro: "ras", free: false},
        {id: 5, name_eng: "ferret", name_ro: "dihor", free: true},
        {id: 6, name_eng: "martin", name_ro: "jder", free: true},
    ],
    DONATIONS: [        
        {type: "crypto", title: "Bitcoin", text: "-", link: "bitcoin:-"},
        {type: "crypto", title: "Ethereum", text: "-"},
        {type: "crypto", title: "Litecoin", text: "-"},
        {type: "crypto", title: "Bitcoin Cash", text: "-"},
        {type: "crypto", title: "Dogecoin", text: "-"},
        {type: "paypal", title: "Paypal", link: "https://paypal.me/oanapopescu93?country.x=RO&locale.x=en_US"},
    ],
    SLOT_PRIZES: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
    RACE_RABBITS: [
        {id: 1, name: "Red", color: "red"},
        {id: 2, name: "Orange", color: "orange"},
        {id: 3, name: "Yellow", color: "yellow"},
        {id: 4, name: "Green", color: "green"},
        {id: 5, name: "Blue", color: "blue"},
        {id: 6, name: "Purple", color: "purple"},
    ],
    CONTACT: [
        {country: "Romania", city: "Bucharest", email: "oanapopescu93@gmail.com", phone: "+40 711 111 111"},
        {country: "USA", city: "New York", email: "oanapopescu93@gmail.com", phone: "+1 111-111-1111"},
        {country: "Germany", city: "Berlin", email: "oanapopescu93@gmail.com", phone: "+49 111 11111111"}
    ]
})