module.exports = Object.freeze({
    products: [
        {table_id: '001', table_name: "roulette", table_type: "european"},
        {table_id: '002', table_name: "roulette", table_type: "american"},
        {table_id: '003', table_name: "roulette", table_type: "european"},
        {table_id: '004', table_name: "roulette", table_type: "american"},
        {table_id: '005', table_name: "blackjack"},
        {table_id: '006', table_name: "blackjack"},
        {table_id: '007', table_name: "blackjack"},
        {table_id: '008', table_name: "slots", table_type: "type1"},
        {table_id: '009', table_name: "slots", table_type: "type2"},
        {table_id: '010', table_name: "slots", table_type: "type1"},
        {table_id: '011', table_name: "slots", table_type: "type2"},
        {table_id: '012', table_name: "slots", table_type: "type1"},
        {table_id: '013', table_name: "craps"},
        {table_id: '014', table_name: "craps"},
        {table_id: '015', table_name: "craps"},
        {table_id: '016', table_name: "craps"},
        {table_id: '017', table_name: "craps"},
    ],
    market: [        
        {id: "garlic", name: "garlic", value:"0.1 carrots", price:0.1, quantity: 1},
        {id: "onion", name: "onion", value:"0.2 carrots", price:0.2, quantity: 1},
        {id: "radish", name: "radish", value:"0.5 carrots", price:0.5, quantity: 1},
        {id: "carrot", name: "carrot", value:"1 carrots", price:1, quantity: 1},
        {id: "turnip", name: "turnip", value:"2 carrots", price:2, quantity: 1},
        {id: "potato", name: "potato", value:"5 carrots", price:5, quantity: 1},
        {id: "cabbage", name: "cabbage", value:"10 carrots", price:10, quantity: 1},
    ],
    profiles: [        
        {id: 1, name_eng: "weasel", name_ro: "nevastuica", free: true},
        {id: 2, name_eng: "fox", name_ro: "vulpe", free: false},
        {id: 3, name_eng: "wolf", name_ro: "lup", free: false},
        {id: 4, name_eng: "lynx", name_ro: "ras", free: false},
        {id: 5, name_eng: "ferret", name_ro: "dihor", free: true},
        {id: 6, name_eng: "martin", name_ro: "jder", free: true},
    ],
    donations: [        
        {type: "crypto", title: "Bitcoin", text: "-", link: "bitcoin:-"},
        {type: "crypto", title: "Ethereum", text: "-"},
        {type: "crypto", title: "Litecoin", text: "-"},
        {type: "crypto", title: "Bitcoin Cash", text: "-"},
        {type: "crypto", title: "Dogecoin", text: "-"},
        {type: "paypal", title: "Paypal", link: "#"},
    ],
    career: [],
})